name = "miniflags"
main = "worker.ts"
compatibility_date = "2025-09-05"

[placement]
mode = "smart"

[build]
command = ""

[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = false

[[durable_objects.bindings]]
name = "FLAGS"
class_name = "FlagStore"

[[migrations]]
tag = "v1"
new_classes = ["FlagStore"]
